### ISSUE TITLE
Incorrect cjs path exported.

### ISSUE THREAD

**Issue by Morgul** [tuplo/envsubst#5]
Attempting to use the library in a typescript project results in:

```
internal/modules/cjs/loader.js:438
      throw e;
      ^

Error: Cannot find module '/Users/morgul/devel/strata-js/tools/strata-queue-monitor/node_modules/@tuplo/envsubst/dist/index.cjs'
    at createEsmNotFoundErr (internal/modules/cjs/loader.js:907:15)
    at finalizeEsmResolution (internal/modules/cjs/loader.js:900:15)
    at resolveExports (internal/modules/cjs/loader.js:432:14)
    at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/morgul/devel/strata-js/tools/strata-queue-monitor/dist/utils/config.js:10:36)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/morgul/devel/strata-js/tools/strata-queue-monitor/node_modules/@tuplo/envsubst/package.json'
}
```

It appears that https://github.com/tuplo/envsubst/blob/main/package.json#L24 should be:

```
"require": "./cjs/index.js", 
```

**Comment by ruicosta042** [comment]
fixed on 1.10.0, cheers

**Comment by Morgul** [comment]
@ruicosta042 It seems like that still doesn't work. I upgraded, and now got a new error:

```
> tsc --project tsconfig.dev.json
internal/modules/cjs/loader.js:1080
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/ccase/devel/stratajs/tools/strata-queue-monitor/node_modules/@tuplo/envsubst/cjs/index.js
require() of ES modules is not supported.
require() of /home/ccase/devel/stratajs/tools/strata-queue-monitor/node_modules/@tuplo/envsubst/cjs/index.js from /home/ccase/devel/stratajs/tools/strata-queue-monitor/dist/utils/config.js is an ES module file as it is a .js file whose nearest parent package.json contains "type":
 "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/ccase/devel/stratajs/tools/strata-queue-monitor/node_modules/@tuplo/envsubst/package.json.
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/ccase/devel/stratajs/tools/strata-queue-monitor/dist/utils/config.js:10:36)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  code: 'ERR_REQUIRE_ESM'
}

Process finished with exit code 1
```

**Comment by ruicosta042** [comment]
I got a e2e test on https://github.com/tuplo/envsubst/tree/main/e2e that succeeds compiling TS `yarn test:ts`

maybe add `"type": "module"` to your package.json?

**Comment by Morgul** [comment]
@ruicosta042 If I specify `"type": "module"`, then I have to move over to esm modules entirely; which kinda defeats the purpose of the `exports` section specifying a cjs version.

As a work around, I've done exactly that, but I have some modules that don't work with esm yet, so I had to fork and modify them, which isn't preferable.

**Comment by ruicosta042** [comment]
hmm, when I remove the "type: module" from my package.json on the E2E test directory, I still can compile to TS.. can you help me reproduce your setup?

**Comment by Morgul** [comment]
I'll try to get a reproduction repo up this evening.

**Comment by Morgul** [comment]
One more thing to try before I get to that: you might need to set your typescript `compilerOptions` to include `"module": "commonjs"`.

**Comment by ruicosta042** [comment]
hey @Morgul fixed on 1.13.0, tested on your test repo

**Comment by Morgul** [comment]
@ruicosta042 That works! Thanks so much!
